tropy/tropy

res/keymaps/project.en.yml, src/components/editable.js, src/components/input.js, src/components/item/panel.js, src/components/item/tab.js, src/components/metadata/field.js, src/components/metadata/index.js, src/components/metadata/list.js, src/components/metadata/panel.js, src/components/note/panel.js, src/components/panel.js, src/components/photo/grid.js, src/components/photo/iterator.js, src/components/photo/list.js, src/components/photo/panel.js, src/components/selection/list.js, src/components/tag/adder.js, src/components/tag/panel.js, src/constants/tabs.js, src/selectors/metadata.js, src/selectors/ontology.js, src/stylesheets/components/_metadata.scss, src/stylesheets/components/_panel.scss, src/stylesheets/components/_tabs.scss, src/stylesheets/components/tag/_list.scss, src/stylesheets/themes/_dark.scss, src/stylesheets/themes/_light.scss, test/selectors/metadata_test.js
=> Panel Focus / Keyboard Navigation

src/components/search/field.js, src/stylesheets/abstracts/_variables.scss, src/stylesheets/components/_search.scss, src/stylesheets/themes/_dark.scss, src/stylesheets/themes/_light.scss
Inukshuk I added a clear button to the search field, it shows/hides depending on wether the input field is empty or not.
=> #90 Add clear button to search field.

res/strings/renderer.en.yml, src/components/esper/esper.js, src/components/item/container.js, src/components/prefs/app.js, src/reducers/settings.js, src/selectors/ui.js
=> Add zoomMode to prefs

package.json, res/keymaps/project.en.yml, res/strings/renderer.en.yml, src/components/button.js, src/components/editor/commands.js, src/components/editor/container.js, src/components/editor/link.js, src/components/editor/schema.js, src/components/editor/selections.js, src/components/editor/toolbar.js, src/components/editor/view.js, src/components/esper/toolbar.js, src/components/slider.js, src/components/toolbar.js, src/stylesheets/abstracts/_variables.scss, src/stylesheets/components/_toolbar.scss, src/stylesheets/components/editor/_styles.scss, src/stylesheets/components/editor/_toolbar.scss, src/window.js, test/editor/commands_test.js, test/fixtures/editor.js
- links can not be updated
- to delete a link, it's text should be deleted
- alt-click to open a link in system browser
- clicking away will close the link menu
- pasting/typing a link will not auto-transform it to a clickable link
----
I've tried to used BufferedInput but was having issues like onBlur would trigger when not desired, or canceling would result in the commit function being called, so I ended up not using it.
=> Notepad links

src/components/editor/plugins.js, src/stylesheets/components/editor/_styles.scss
=> persistent selection

src/commands/note.js
Beginning of the French translation
renderer.fr.yml and app.fr.yml are on their way (ca. 50% done), not using Transifex though.
=> Create browser.fr.yml 

src/components/editor/alignment.js, src/components/editor/commands.js, src/components/editor/schema.js, src/components/editor/toolbar.js, src/stylesheets/components/editor/_styles.scss
=> Notepad: alignment

res/menu/app.fr.yml, res/strings/renderer.fr.yml
I guess that despite this [post](https://forums.tropy.org/t/translation-of-tropy/299/2), project.en.yml has not to be translated (I don't see what has to be done).
As for context.en.yml, do you prefer me using Transifex to complete the translation or keeping on using GitHub?
=> French translation 2-3/4

res/keymaps/project.en.yml, res/strings/renderer.en.yml, src/components/editor/schema.js, src/components/editor/toolbar.js, src/components/icons.js
Need to decide if we want to solve it this way or with unicode/diacritics - until then, it's on hold.
An argument against diacritics is that some special characters can not be combined with a macron: https://en.wikipedia.org/wiki/Scribal_abbreviation#Unicode_encoding
=> Notepad: overline

src/commands/import.js, src/common/cache.js, src/components/item/cover-image.js, src/components/photo/iterable.js, src/components/photo/thumbnail.js, src/constants/index.js, src/constants/mime.js, src/dialog.js, src/exif.js, src/image.js
=> SVG Support

res/menu/context.en.yml, src/browser/menu.js, src/browser/tropy.js, src/components/editor/schema.js, src/components/item/container.js, src/components/item/view.js, src/components/note/pad.js, src/reducers/ui.js, src/selectors/ui.js, src/stylesheets/abstracts/_variables.scss, src/stylesheets/components/_resizable.scss, src/stylesheets/components/editor/_styles.scss, src/stylesheets/components/editor/_view.scss, src/stylesheets/components/item/_view.scss, src/stylesheets/themes/_dark.scss, src/stylesheets/themes/_light.scss
Later:
* Change defaults (preferences)
* Right to left
See https://forums.tropy.org/t/vertical-writing/372/2
Closes #178
=> NotePad Settings

package-lock.json, package.json, res/menu/app.en.yml, src/browser/tropy.js, src/common/plugins.js, src/window.js, test/common/plugins_test.js
=> Simple plugin installer

.travis.yml, package-lock.json, package.json, res/strings/renderer.en.yml, src/export/export.js, test/export/export_test.js
=> Update to JSON-LD 1.1

src/components/editor/view.js, src/components/esper/esper.js, src/components/iterator.js, src/components/panel.js
=> Use resize observer content rect directly

db/migrate/project/1810082056.add-project-base.sql, db/schema/project.sql, res/menu/app.de.yml, res/menu/app.en.yml, res/menu/app.fr.yml, res/menu/app.ja.yml, res/strings/renderer.en.yml, src/actions/project.js, src/actions/wizard.js, src/browser/tropy.js, src/commands/item.js, src/commands/photo.js, src/commands/project.js, src/common/query.js, src/components/button.js, src/components/metadata/field.js, src/components/photo/info.js, src/components/wizard/container.js, src/components/wizard/project.js, src/constants/project.js, src/models/photo.js, src/models/project.js, src/selectors/metadata.js, test/common/query_test.js
=> Support relative photo paths

package-lock.json, package.json, src/commands/import.js, src/commands/photo.js, src/commands/selection.js, src/components/item/panel.js, src/components/photo/grid.js, src/components/photo/iterable.js, src/components/photo/list-item.js, src/components/selection/iterable.js, src/components/selection/iterator.js, src/image/image.js, src/image/xmp.js
=> Selection thumbnails

package-lock.json, package.json, res/menu/app.de.yml, res/menu/app.en.yml, res/menu/app.fr.yml, res/menu/app.it.yml, res/menu/app.ja.yml, scripts/build.js, scripts/sign.js, src/browser/dialog.js, src/browser/idle.js, src/browser/main.js, src/browser/menu.js, src/models/item.js, test/browser/idle_test.js
=> Electron 6

.eslintrc, res/menu/context.en.yml, res/strings/renderer.en.yml, src/actions/metadata.js, src/browser/tropy.js, src/commands/metadata.js, src/common/util.js, src/components/item/panel.js, src/components/metadata/field.js, src/components/metadata/list.js, src/components/metadata/panel.js, src/components/resource/select.js, src/components/select.js, src/selectors/metadata.js, src/stylesheets/components/_select.scss, src/window.js, test/common/util_test.js, test/selectors/metadata_test.js
=> Improve add-new-metadata-field handling

package-lock.json, package.json, src/components/esper/esper.js, src/constants/mime.js, src/image/image.js
This already works, but requires libvips linked to libheif.
Closes #386
=> Add HEIF support

res/menu/app.en.yml, res/menu/context.en.yml, src/actions/item.js, src/browser/tropy.js, src/commands/item.js, src/commands/photo.js, src/components/esper/esper.js, src/components/list/node.js, src/components/photo/iterable.js, src/components/photo/iterator.js, src/components/project/name.js, src/components/project/view.js, src/components/selection/iterable.js, src/constants/mime.js, src/dialog.js, src/image/image.js, src/models/photo.js
=> Import remote photos

src/components/metadata/field.js
=> Adds drag & drop text functionality to MetadataField

src/common/iiif.js, src/components/item/cover-image.js, src/components/item/drag-preview.js, src/components/item/table-cell.js, src/components/item/tile.js, src/components/photo/drag-preview.js, src/components/photo/iterable.js, src/components/photo/iterator.js, src/components/photo/thumbnail.js, src/components/print/photo.js, src/image/image.js, src/stylesheets/components/_cover-image.scss, src/stylesheets/components/_drag-layer.scss, src/stylesheets/components/_thumbnail.scss, src/stylesheets/components/item/_table.scss, src/stylesheets/components/photo/_list.scss, src/stylesheets/partials/_tile.scss
=> Preserve image aspect ratio in thumbnails

package-lock.json, package.json, src/components/esper/selection.js, src/components/esper/view.js, src/views/project.js
=> Update to Pixi.js 5

res/strings/renderer.en.yml, src/components/editor/link.js, src/components/editor/toolbar.js, src/components/editor/view.js, src/components/icons.js, src/editor/commands.js, src/editor/schema.js, src/editor/selections.js, src/stylesheets/components/editor/_styles.scss
=> Improve notepad link tool

res/strings/renderer.en.yml, src/commands/item/print.js, src/commands/photo/extract.js, src/common/iiif.js, src/common/util.js, src/components/esper/container.js, src/components/prefs/app.js, src/components/print/photo.js, src/esper/index.js, src/reducers/settings.js
=> Improve print / PDF
